{!! Html::script('assets/jquery/dist/jquery.min.js') !!}
{!! Html::script('assets/bootstrap-3.3.7-dist/js/bootstrap.min.js') !!}
{!! Html::script('assets/js/slick.min.js') !!}
{!! Html::script('assets/js/nouislider.min.js') !!}
{!! Html::script('assets/js/jquery.zoom.min.js') !!}
{!! Html::script('assets/sweetalert2/dist/sweetalert2.min.js') !!}
{!! Html::script('assets/js/main.js') !!}
{!! Html::script('js/user/main.js') !!}
{!! Html::script('js/user/cart.js') !!}
